### Obtener todos los libros
GET http://localhost:3000/api/libros


### Obtener un libro por ID
GET http://localhost:3000/libros/1


### Crear un libro
POST http://localhost:3000/libros
Content-Type: application/json


{
"titulo": "1984",
"autor": "George Orwell",
"anio": 1949
}


### Actualizar un libro
PUT http://localhost:3000/libros/1
Content-Type: application/json


{
"titulo": "Fahrenheit 451 (Edición actualizada)",
"anio": 1954
}


### Eliminar un libro
DELETE http://localhost:3000/libros/2